"""
issue-runner 스킬: GitHub 이슈 기반 자동 코드 수정

Coordinator Agent가 사용하는 스킬입니다.
GitHub 이슈를 기반으로 자동 코드 수정 및 커밋을 수행합니다.
"""

import json
import subprocess
from pathlib import Path
from datetime import datetime


class IssueRunner:
    """GitHub 이슈 기반 자동 수정"""

    def __init__(self):
        self.workspace_dir = Path("/workspace/data")
        self.workspace_dir.mkdir(parents=True, exist_ok=True)

    def read_issues(self) -> list[dict]:
        """생성된 이슈 읽기"""
        input_file = self.workspace_dir / "created_issues.json"

        if not input_file.exists():
            print("[IssueRunner] 생성된 이슈를 찾을 수 없습니다.")
            return []

        with open(input_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        return data.get("issues", [])

    def analyze_issue(self, issue: dict) -> dict:
        """이슈 분석 및 해결 방안 도출"""
        analysis = {
            "issue_id": issue.get("id"),
            "title": issue.get("title"),
            "required_actions": [],
            "code_changes": [],
            "estimated_effort": "medium"
        }

        # 카테고리별 분석
        labels = issue.get("labels", [])

        if "news-analysis" in labels:
            analysis["required_actions"].append("뉴스 분석 파이프라인 개선")

            if "기술" in issue.get("title", ""):
                analysis["code_changes"].append({
                    "file": "modules/ai_analyzer.py",
                    "change_type": "enhancement",
                    "description": "기술 영향도 분석 알고리즘 개선"
                })

            if "정책" in issue.get("title", ""):
                analysis["code_changes"].append({
                    "file": "modules/news_collector.py",
                    "change_type": "feature",
                    "description": "정책 관련 뉴스 필터링 강화"
                })

        return analysis

    def generate_fix(self, analysis: dict) -> dict:
        """자동 수정 코드 생성"""
        fix = {
            "issue_id": analysis.get("issue_id"),
            "status": "analyzed",
            "changes": [],
            "branch": f"fix/issue-{analysis['issue_id']}",
            "commit_message": self._generate_commit_message(analysis),
            "ready_for_commit": False
        }

        # 각 코드 변경사항에 대해 수정 생성
        for change in analysis.get("code_changes", []):
            fix_code = {
                "file": change.get("file"),
                "type": change.get("change_type"),
                "description": change.get("description"),
                "implementation": self._generate_implementation(change)
            }
            fix["changes"].append(fix_code)

        # 충분한 변경사항이 있으면 커밋 준비 완료
        if len(fix["changes"]) > 0:
            fix["ready_for_commit"] = True

        return fix

    def _generate_implementation(self, change: dict) -> str:
        """구현 코드 생성"""
        change_type = change.get("change_type")
        description = change.get("description")

        if change_type == "enhancement":
            return f"""
# {description}
# 다음 함수를 개선하세요:

def analyze_technical_impact(article: dict) -> str:
    \"\"\"
    기술 영향도 분석 알고리즘 개선
    - 더 세밀한 기술 분류
    - 산업 동향 반영
    - 경쟁사 기술 비교
    \"\"\"
    # TODO: 구현
    pass
"""

        elif change_type == "feature":
            return f"""
# {description}
# 다음 함수를 추가하세요:

def filter_by_policy_keywords(articles: list[dict]) -> list[dict]:
    \"\"\"
    정책 관련 뉴스 필터링 강화
    - 법규 변화
    - 환경 규제
    - 정부 지원 정책
    \"\"\"
    POLICY_KEYWORDS = [
        "규제", "환경", "법규", "정책", "보조금",
        "탄소중립", "전기차", "배출가스", "안전기준"
    ]
    # TODO: 구현
    pass
"""
        else:
            return "# TODO: 구현"

    def _generate_commit_message(self, analysis: dict) -> str:
        """커밋 메시지 생성"""
        actions = analysis.get("required_actions", [])
        action_text = actions[0] if actions else "자동 수정"

        return f"""fix: {action_text}

Issues:
- {analysis['title']}

Changes:
- {len(analysis.get('code_changes', []))}개 파일 변경

Auto-generated by News Automation Harness
Issue #{analysis.get('issue_id')}"""

    def execute_fixes(self, issues: list[dict]) -> dict:
        """이슈 수정 실행"""
        fixes = []
        total_issues = len(issues)

        print(f"[IssueRunner] {total_issues}개 이슈 처리 중...")

        for i, issue in enumerate(issues, 1):
            print(f"[IssueRunner] {i}/{total_issues} 분석: {issue['title'][:40]}")

            # 이슈 분석
            analysis = self.analyze_issue(issue)

            # 수정 생성
            fix = self.generate_fix(analysis)
            fixes.append(fix)

            # 커밋 준비 완료인 경우
            if fix.get("ready_for_commit"):
                print(f"[IssueRunner]   ✅ {fix['branch']}로 커밋 준비됨")

        return {
            "status": "completed",
            "total_issues": total_issues,
            "fixes": fixes,
            "ready_to_commit": sum(1 for f in fixes if f.get("ready_for_commit")),
            "execution_time": datetime.now().isoformat()
        }

    def run(self) -> dict:
        """전체 이슈 실행 파이프라인"""
        # 이슈 읽기
        issues = self.read_issues()

        if not issues:
            print("[IssueRunner] 처리할 이슈가 없습니다.")
            return {
                "status": "no_issues",
                "message": "생성된 이슈가 없습니다."
            }

        # 이슈 처리
        result = self.execute_fixes(issues)

        # 결과 저장
        output_file = self.workspace_dir / "issue_runner_result.json"
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)

        print(f"[IssueRunner] 처리 완료: {output_file}")
        print(f"[IssueRunner] 준비된 커밋: {result['ready_to_commit']}/{result['total_issues']}")

        return result


def run_skill() -> dict:
    """스킬 실행"""
    runner = IssueRunner()
    return runner.run()


if __name__ == "__main__":
    result = run_skill()
    print("\n=== 이슈 실행 결과 ===")
    print(f"상태: {result.get('status')}")
    print(f"총 이슈: {result.get('total_issues')}")
    print(f"준비된 커밋: {result.get('ready_to_commit')}")
